import Head from "next/head";

const Header = () => {
  return (
    <Head>
      <title>Blogr</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo/blog.ico" />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Overpass:wght@300;600&family=Quicksand:wght@300;400;500;600&family=Roboto:wght@300;400;500;700;900&family=Ubuntu:wght@400;500;700&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
};

export default Header;
